services:
  frontend:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    image: node:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - PORT=8000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
